spring.application.name=ejercicioMongo

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=ut6_a3_db
spring.data.mongodb.uri=mongodb://localhost:27017/ut6_a3_db
server.port=80
