spring.application.name=psep-ut4-api-server

# modo de arranque: server o client
app.mode=server

server.port=8080

# BD (solo se usa en modo server)
spring.datasource.url=jdbc:mysql://localhost:3306/psep_ut4_api?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8

# Cliente (base URL del servidor)
client.base-url=http://localhost:8080