spring.application.name=psep-ut4-api-server

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3308/psep_ut4?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

logging.file.name=logs/psep-api.log
logging.level.com.example.psep_ut4_api_server.server=INFO


